on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  run-release-tool:
    uses: Kareadita/GitHubActions/.github/workflows/release-tools.base.yml@main
    secrets: inherit
    with:
      config-path: publish.yaml
