on:
  pull_request:
    types: [closed]
    branches: ["main"]

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  run-release-tool:
    if: github.event.pull_request.merged == true
    uses: Kareadita/GitHubActions/.github/workflows/release-tools.base.yml@main
    secrets: inherit
    with:
      config-path: publish.yaml
